<table>
	<tr>
		<td style="text-align: right;">Telephone:</td>
		<td><a href="tel:<?php echo preg_replace('/\.|\-|\(|\)| /', '', $this->site->phone); ?>"><?php echo $this->site->phone; ?></a></td>
	</tr>
	<tr>
		<td style="text-align: right;">Hours of Operation:</td>
		<td>Open <strong>364</strong> days a year!<br>Available for emergencies <strong>24x7</strong></td>
	</tr>
</table>
<form name="contact_form" method="<?php echo $this->site->getFormInfo('contact_form', 'method'); ?>" action="<?php echo $this->site->getFormInfo('contact_form', 'action'); ?>" data-ajax="false">
	<ol><?php echo join(' ', $this->site->getFormInfo('contact_form', 'fields')); ?></ol>
	<p>
		<input type="hidden" name="fns" value="contact_form">
		<input type="submit" name="submit_save" value="Submit">
	</p>
</form>
<script type="text/javascript" src="/js/validate.jquery.js"></script>
<script type="text/javascript"><!--
var submissionCallback = (function(){
	document.location.href = "/thank-you";
});

$(document).ready(function(){
	$("form").validate({
		ajax: true,
		ajaxCallback: "submissionCallback"
	});
});
--></script>
