<p class="banner" id="need-service-2">
	<strong>Need Help Now?</strong>
	<span>Call <a href="tel:7578902600">757-800-2000</a> or <a href="/schedule-appointment" data-ajax="false">click here</a> to schedule your next appointment.</span>
	<a href="/schedule-appointment" data-ajax="false" id="need-service-button"><span>Schedule Appointment!</span></a>
</p>
<h2 style="margin-top: 0;">jQuery Example Site is ...</h2>
<ul>
	<li>Fast</li>
	<li>Expert</li>
	<li>Quality</li>
	<li>Excellent</li>
</ul>