<!doctype html>
<html>
	<head>
		<title><?php echo $this->site->name .' | '. $this->title; ?></title>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<meta name="Keywords" content="<?php echo $this->site->metakeywords; ?>">
		<meta name="Description" content="<?php echo $this->site->metadescription; ?>">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
		<meta name="robots" content="noindex, nofollow">
		<script type="text/javascript" src="/js/jquery.js"></script>
		<script type="text/javascript" src="<?php echo $this->stylePath; ?>js/jquery-mobile.js"></script>
		<link rel="stylesheet" type="text/css" href="<?php echo $this->stylePath; ?>css/jquery-mobile.css">
		<link rel="stylesheet" type="text/css" href="<?php echo $this->stylePath; ?>css/layout.css">
	</head>
	<body>
		<div data-role="page">
			<header data-role="header">
				<h1><?php echo $this->title; ?></h1>
			</header>
			<div data-role="content">
				<p id="logo"><a href="/"><img src="<?php echo $this->stylePath; ?>img/logo.png" alt="<?php echo $this->site->name; ?>"></a></p>
				<?php 
					echo $this->content;
					echo $this->navigation; 
				?>
			</div>
			<footer>
				<p id="social-links">
					<a href="http://www.facebook.com/example" class="external" id="facebook"><span>Facebook</span></a>
					<a href="http://www.youtube.com/user/example" class="external"><span>YouTube</span></a>
					<br class="clear">
				</p>
				<p>&copy;<?php echo date('Y'); ?> <?php echo $this->site->name; ?>.  All rights reserved.</p>
				<a href="<?php echo $this->site->fullsiteurl; ?>" data-ajax="false">View Full Site</a>
			</footer>
		</div>
		<script type="text/javascript"><!--
			$(document).ready(function(){
				$("a.external").attr("target", "_blank");
			});
		--></script>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-6767594-5']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
	</body>
</html>
