<!doctype html>
<html>
	<head>
		<title><?php echo $this->site->name .' | '. $this->title; ?></title>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<meta name="Keywords" content="<?php echo $this->site->metakeywords; ?>">
		<meta name="Description" content="<?php echo $this->site->metadescription; ?>">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
		<meta name="robots" content="noindex, nofollow">
		<link rel="stylesheet" type="text/css" href="<?php echo $this->stylePath; ?>css/layout.css">
	</head>
	<body>
		<header>
			<a href="/">
				<img src="<?php echo $this->stylePath; ?>img/logo.png" alt="<?php echo $this->site->name; ?>">
				<strong><?php echo $this->site->name; ?></strong>
			</a>
		</header>
		<div id="content">
			<?php 
				echo $this->content;
			 	echo $this->navigation; 
			 ?>
		</div>
		<footer>
			<p>&copy;<?php echo date('Y'); ?> <?php echo $this->site->name; ?>.  All rights reserved.</p>
			<a href="<?php echo $this->site->fullsiteurl; ?>">View Full Site</a>
		</footer>
	</body>
</html>